name: Typo-corrector

run-name: Typo Corrector
on: push

jobs:
  proselint:
    name: Proselint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Proselint
        uses: dhruvmanila/action-proselint@master
